import { z } from '../z.ts';

// TODO split up in separate schemas
export const jobResponseSchema = z.enum([
  //Directing jobs
  'Action Director',
  'Additional Second Assistant Director',
  'Additional Third Assistant Director',
  'Assistant Director',
  'Assistant Director Trainee',
  'Co-Director',
  'Continuity',
  'Crowd Assistant Director',
  'Director',
  'Field Director',
  'First Assistant Director',
  'First Assistant Director (Prep)',
  'First Assistant Director Trainee',
  'Insert Unit Director',
  'Insert Unit First Assistant Director',
  'Layout',
  'Other',
  'Script Coordinator',
  'Script Supervisor',
  'Second Assistant Director',
  'Second Assistant Director Trainee',
  'Second Second Assistant Director',
  'Second Unit Director',
  'Second Unit First Assistant Director',
  'Series Director',
  'Special Guest Director',
  'Stage Director',
  'Third Assistant Director',

  //Writing jobs
  'Adaptation',
  'Author',
  'Book',
  'Characters',
  'Co-Writer',
  'Comic Book',
  'Creative Producer',
  'Dialogue',
  'Executive Story Editor',
  'Graphic Novel',
  'Head of Story',
  'Idea',
  'Junior Story Editor',
  'Lyricist',
  'Musical',
  'Novel',
  'Opera',
  'Original Concept',
  'Original Film Writer',
  'Original Series Creator',
  'Original Story',
  'Other',
  'Scenario Writer',
  'Screenplay',
  'Screenstory',
  'Script Consultant',
  'Script Editor',
  'Senior Story Editor',
  'Series Composition',
  'Short Story',
  'Staff Writer',
  'Story',
  'Story Artist',
  'Story Consultant',
  'Story Coordinator',
  'Story Developer',
  'Story Editor',
  'Story Manager',
  'Story Supervisor',
  'Storyboard',
  'Teleplay',
  'Texte',
  'Theatre Play',
  'Writer',
  `Writers' Assistant`,
  `Writers' Production`,
]);
