name: The Trial of Truth aka CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: The Interrogation Room (Test)
    runs-on: ubuntu-latest

    steps:
      - name: Secure the Evidence aka Checkout Code
        uses: actions/checkout@v4

      - name: Summon the Digital Oracle aka Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Gather the Tools aka Install Dependencies
        run: 'deno task install'

      - name: Probe the Client's Mind aka Run Tests
        working-directory: projects/client
        run: 'deno run test:unit'
