name: The Gatekeeper's Grimoire aka PR Gate

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  commitlint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Unveiling the Code Codex
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scrutinizing the Commit Chronicle
        uses: wagoid/commitlint-github-action@v3

      - name: Exterminating the Fixup Fiends
        uses: vladjerca/no-fixups-action@main
        with:
          skip-checkout: true
